# Generated by Django 3.2.15 on 2022-09-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=128)),
                ('correo_cliente', models.EmailField(max_length=512)),
                ('telefono_cliente', models.PositiveBigIntegerField()),
                ('mensaje_cliente', models.CharField(max_length=1024)),
            ],
        ),
    ]
