# Generated by Django 3.2.15 on 2022-09-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='precio',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
