# Generated by Django 3.2.15 on 2022-09-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_platillo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='popularidad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
